[theme]
base = "light"
primaryColor = "#5361d8"
backgroundColor = "#f3f5fa"
secondaryBackgroundColor = "#edf1f8"
textColor = "#202c43"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"

[client]
toolbarMode = "viewer"
