[theme]
base = "light"
primaryColor = "#087f8c"
backgroundColor = "#f5f7fb"
secondaryBackgroundColor = "#eaf0f7"
textColor = "#17324d"
font = "sans serif"

[browser]
gatherUsageStats = false

[server]
address = "127.0.0.1"

[client]
toolbarMode = "viewer"
